spring.application.name=spring-demo

# H2 Database Console
spring.h2.console.path=/h2-console
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=123123

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Server
server.port=4000

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6380
# Make Redis connection timeout shorter for faster failure
spring.data.redis.timeout=2000
spring.data.redis.connect-timeout=2000


# Expose the Prometheus metrics endpoint
management.endpoints.web.exposure.include=health,info,prometheus
# Enable additional metrics for better visibility
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
